# Estágio de build do Angular
FROM node:22.0 AS build

WORKDIR /app
COPY . .

RUN npm install
RUN npm install -g @angular/cli@latest

# Build da aplicação Angular
RUN ng build --configuration=production
RUN ls -la /app/dist

# Estágio de produção com Nginx
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
COPY mime.types /etc/nginx/mime.types

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
