services:
  postgres:
    image: 'postgres:16-alpine'
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${POSTGRES_USER}"
    ports:
      - '5432:5432'
    expose:
      - '5432'
    networks:
      - net-login-page-authentication

networks:
  net-login-page-authentication:
    driver: bridge
